# Generated by Django 4.2.16 on 2024-11-20 05:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_post_like_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='time',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='name',
            new_name='location',
        ),
        migrations.RemoveField(
            model_name='event',
            name='eventChannel',
        ),
        migrations.RemoveField(
            model_name='event',
            name='host',
        ),
        migrations.RemoveField(
            model_name='event',
            name='tags',
        ),
        migrations.AddField(
            model_name='event',
            name='allergy_friendly',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='event',
            name='food_type',
            field=models.CharField(default='Unknown', max_length=50),
        ),
        migrations.AddField(
            model_name='event',
            name='group_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='host_type',
            field=models.CharField(default='Host', max_length=50),
        ),
        migrations.AddField(
            model_name='event',
            name='preferences',
            field=models.CharField(default='Any', max_length=100),
        ),
        migrations.AddField(
            model_name='event',
            name='title',
            field=models.CharField(default='Untitled Event', max_length=100),
        ),
        migrations.CreateModel(
            name='Workshop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('time', models.DateTimeField()),
                ('tags', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('photos', models.ImageField(blank=True, null=True, upload_to='workshop_photos/')),
                ('video_url', models.URLField(blank=True, null=True)),
                ('eventChannel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.channel')),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.user')),
            ],
        ),
    ]
